import { Provider } from '@/components/ui/provider'
import {Box, ClientOnly, Flex} from '@chakra-ui/react';
import MySidebar from '@/components/layout/MySidebar';

export const metadata = {
    title: 'L5R База знаний',
    description: 'Generated by create next app',
};



export default function RootLayout({ Component, pageProps }) {
    return (
        <Provider>
            <ClientOnly>
                <Flex>
                        <MySidebar />
                        <Box
                            flex="1"
                            p={{
                                base: 2,
                                lg: 6,
                            }}
                            ml={{
                                base: '0px',
                                lg: '65px',
                            }}
                            mb='0px'
                            width={{
                                base: '100%',
                                sm: '400px',
                                md: '768px',
                                lg: '1024px',
                                xl: '1280px',
                                '2xl': '1536px',
                            }}
                            height={{
                                base: 'calc(100vh - 75px)',
                                lg: '100%',
                            }}
                            overflow={'auto'}
                        >
                            <Component {...pageProps} />
                        </Box>
                </Flex>
            </ClientOnly>
        </Provider>
    );
}
