import { Provider } from "@/components/ui/provider";
import { Box, ClientOnly, Flex } from "@chakra-ui/react";
import MySidebar from "@/components/layout/MySidebar";

import "@/styles/table.css";
import "@/styles/card-preview.css";
// import { techniquesRouteData } from "@/mockData/routeData/techniques";
// import { groups, translations } from "@/mockData/routeData/constants";
// import { skillsRouteData } from "@/mockData/routeData/skills";

export const metadata = {
  title: "L5R База знаний",
  description: "Generated by create next app",
};

console.clear();
// console.log(
//   Object.fromEntries(
//     // Object.entries(techniquesRouteData)
//     Object.entries(skillsRouteData)
//       // .filter((group) => group[0] !== groups.techniques)
//       .map(([key, item]) => {
//         const newItem = Object.fromEntries(
//           Object.entries(item.list).map(([_, jValue]) => {
//             return [jValue.title, jValue.key];
//           })
//         );
//
//         return [translations[key], newItem];
//       })
//   )
// );

export default function RootLayout({ Component, pageProps }) {
  return (
    <Provider>
      <ClientOnly>
        <Flex position={"relative"}>
          <MySidebar />
          <Box
            flex="1"
            p={{ base: 2, lg: 6 }}
            ml={{ base: "0px", lg: "65px" }}
            mb="0px"
            height={{ base: "calc(100dvh - 70px)", lg: "100vh" }}
            width={{
              base: "100%",
              sm: "400px",
              md: "768px",
              lg: "1024px",
              xl: "1280px",
              "2xl": "1536px",
            }}
          >
            <Component {...pageProps} />
          </Box>
        </Flex>
      </ClientOnly>
    </Provider>
  );
}
