import { Box, Flex } from "@chakra-ui/react";

import { Provider as ChakraProvider } from "@/components/ui/provider";
import { MySidebar } from "@/components/layout/MySidebar";
import { MyAlerts } from "@/components/layout/MyAlerts";

import "quill/dist/quill.core.css";
import "quill/dist/quill.snow.css";
import "@/styles/alert.css";
import "@/styles/scrollbar.css";
import "@/styles/table.css";
import "@/styles/card-preview.css";
import "@/styles/star-elements.css";

import favicon from "@/static/images/icons/favicon-32x32.png";

import { AlertProvider } from "@/providers/AlertProvider";
import Head from "next/head";

export const metadata = {
  title: "L5R База знаний",
  description: "Generated by create next app",
};

console.clear();

export default function RootLayout({ Component, pageProps }) {
  return (
    <ChakraProvider>
      <Head>
        <meta charSet="UTF-8" />
        <title>{Component?.metaData?.title}</title>
        <meta name="description" content={Component?.metaData?.title} />
        <link rel="icon" href={favicon.src} />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
          key="viewport"
        />
      </Head>

      <AlertProvider>
        <Flex position={"relative"}>
          <MySidebar />
          <MyAlerts />
          <Box
            flex="1"
            px={{ base: 2, lg: 6 }}
            py={{ base: 1, lg: 2 }}
            ml={{ base: "0px", lg: "60px" }}
            mb="0px"
            height={{ base: "calc(100dvh - 60px)", lg: "100vh" }}
            width={{
              base: "100%",
              sm: "400px",
              md: "768px",
              lg: "1024px",
              xl: "1280px",
              "2xl": "1536px",
            }}
          >
            <Component {...pageProps} />
          </Box>
        </Flex>
      </AlertProvider>
    </ChakraProvider>
  );
}
