import localFont from 'next/font/local';
import { Provider } from '@/components/ui/provider'
import {ClientOnly} from '@chakra-ui/react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'L5R База знаний',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <ClientOnly>
            <div>
              {children}
            </div>
          </ClientOnly>
        </Provider>
      </body>
    </html>
  );
}
